#this is where I will write the seed data for my database
Dish.create(name: "Roasted Beets", dish_type: "Side")
Dish.create(name: "Roast Turkey", dish_type: "Main")
Dish.create(name: "Garlic Mashed Potatoes", dish_type: "Side")
Dish.create(name: "Beet and Citrus Salad with Pine Nut Vinaigrette ", dish_type: "Salad")
Dish.create(name: "Beef Tenderloin with Shallot and Red Wine Reduction", dish_type: "Main")
Dish.create(name: "Green Bean Casserole", dish_type: "Side")
Dish.create(name: "Sweet Potato Casserole", dish_type: "Side")
Dish.create(name: "Turkey Gravy", dish_type: "Side")
Dish.create(name: "Parker-House Rolls", dish_type: "Bread")
Dish.create(name: "Pumpkin Cheese Cake", dish_type: "Dessert")
Dish.create(name: "Ginger Glazed Mahi-Mahi", dish_type: "Main")
Dish.create(name: "Glazed Easter Ham", dish_type: "Main")
Dish.create(name: "Bacon-Potato Corn Chowder", dish_type: "Soup")
Dish.create(name: "Braised Short Ribs", dish_type: "Main")
Dish.create(name: "Brown Sugar and Bacon Baked Beans", dish_type: "Side")
Dish.create(name: "Roasted Aspargus", dish_type: "Side")
Dish.create(name: "Chex Party Mix", dish_type: "Appetizer")
Dish.create(name: "Cream Cheese with Pick-A-Pepper Sauce", dish_type: "Appetizer")
Dish.create(name: "Chocolate Amaretto-Espresso Mousse Cake", dish_type: "Dessert")
Dish.create(name: "Classic Deviled Eggs", dish_type: "Side")
Dish.create(name: "Cranberry Brie Bites", dish_type: "Appetizer")
Dish.create(name: "Limoncello Cheesecake", dish_type: "Dessert")
Dish.create(name: "Lamb Chops with Fresh Fig Pan Sauce", dish_type: "Main")
Dish.create(name: "LT Backyard Burger", dish_type: "Main")
Dish.create(name: "Mashed Cauliflower Green Bean Casserole", dish_type: "Side")
